produits:
    path:     /
    defaults: { _controller: EcommerceBundle:Produits:produits }

presentation:
    path:     /produit/{id}
    defaults: { _controller: EcommerceBundle:Produits:presentation }
    
rechercheproduit:
    path:     /recherche
    defaults: { _controller: EcommerceBundle:Produits:rechercheTraitement }